<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>YoutubeTV</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>../../../7DaysToDie.app/Contents/Resources/Data/Managed/Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>../../../7DaysToDie.app/Contents/Resources/Data/Managed/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>../../0_TFP_Harmony/0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>../../../7DaysToDie.app/Contents/Resources/Data/Managed/UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>../../../7DaysToDie.app/Contents/Resources/Data/Managed/UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="Python.Runtime">
      <HintPath>../Python.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>../../../7DaysToDie.app/Contents/Resources/Data/Managed/UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="LogLibrary">
      <HintPath>../../../7DaysToDie.app/Contents/Resources/Data/Managed/LogLibrary.dll</HintPath>
    </Reference>
    <Reference Include="InControl">
      <HintPath>../../../7DaysToDie.app/Contents/Resources/Data/Managed/InControl.dll</HintPath>
    </Reference>
    <Reference Include="NGUI">
      <HintPath>../../../7DaysToDie.app/Contents/Resources/Data/Managed/NGUI.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CSharp">
      <HintPath>../Microsoft.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>../../../7DaysToDie.app/Contents/Resources/Data/Managed/UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
