using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Threading;
using LibVLCSharp.Shared;

const int width = 1280;
const int height = 720;
const int bpp = 4;
var url = args[0];
var vlcDir = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "libvlc", "win-x64"));
Console.WriteLine("vlcDir=" + vlcDir);
Core.Initialize(vlcDir);
byte[] frame = new byte[width * height * bpp];
var handle = GCHandle.Alloc(frame, GCHandleType.Pinned);
var gotFrame = new ManualResetEventSlim(false);
using var libvlc = new LibVLC("--no-video-title-show", "--quiet", "--network-caching=250", "--live-caching=250");
using var mp = new MediaPlayer(libvlc);
MediaPlayer.LibVLCVideoLockCb lockCb = (_, planes) => { Marshal.WriteIntPtr(planes, handle.AddrOfPinnedObject()); return IntPtr.Zero; };
MediaPlayer.LibVLCVideoUnlockCb unlockCb = (_, __, ___) => gotFrame.Set();
MediaPlayer.LibVLCVideoDisplayCb displayCb = (_, __) => {};
mp.SetVideoFormat("RV32", width, height, (uint)(width * bpp));
mp.SetVideoCallbacks(lockCb, unlockCb, displayCb);
mp.EncounteredError += (_, __) => Console.WriteLine("vlc_error");
using var media = new Media(libvlc, new Uri(url));
media.AddOption(":demux=ts");
mp.Play(media);
var ok = gotFrame.Wait(TimeSpan.FromSeconds(10));
Console.WriteLine("first_frame=" + ok);
mp.Stop();
handle.Free();
Environment.Exit(ok ? 0 : 2);
